name: Detect secrets

on: push

jobs:
  detect-secrets:
    name: scan+audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Secret Scanner
        uses: bigpick/ibm-detect-secrets-action@0.1.0
