name: Detect secrets

on: push

jobs:
  detect-secrets:
    name: Check for secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Secret Scanner
        uses: bigpick/ibm-detect-secrets-action@0.0.0+build4
