name: "Conventional commit PR title"

on:
  pull_request_target:
  pull_request:

permissions:
  pull-requests: read

jobs:
  validate-pr-title:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
